-- MySQL Script generated by MySQL Workbench
-- 10/07/16 01:18:49
-- Model: ERD Boxsteps    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema boxsteps
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema boxsteps
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `boxsteps` DEFAULT CHARACTER SET utf8 ;
USE `boxsteps` ;

-- -----------------------------------------------------
-- Table `boxsteps`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boxsteps`.`roles` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `role` VARCHAR(50) NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`));

CREATE UNIQUE INDEX `uq_role` ON `boxsteps`.`roles` (`role` ASC);


-- -----------------------------------------------------
-- Table `boxsteps`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boxsteps`.`users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `second_name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `login` VARCHAR(50) NOT NULL,
  `password` VARCHAR(50) NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `roles_id` INT UNSIGNED NOT NULL,
  `users_id` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_users_roles`
    FOREIGN KEY (`roles_id`)
    REFERENCES `boxsteps`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `boxsteps`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE UNIQUE INDEX `uq_email` ON `boxsteps`.`users` (`email` ASC);

CREATE UNIQUE INDEX `uq_login` ON `boxsteps`.`users` (`login` ASC);

CREATE INDEX `fk_users_roles_idx` ON `boxsteps`.`users` (`roles_id` ASC);

CREATE INDEX `fk_users_users_idx` ON `boxsteps`.`users` (`users_id` ASC);


-- -----------------------------------------------------
-- Table `boxsteps`.`messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boxsteps`.`messages` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `message` TEXT NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `users_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_messages_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `boxsteps`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE INDEX `fk_messages_users_idx` ON `boxsteps`.`messages` (`users_id` ASC);


-- -----------------------------------------------------
-- Table `boxsteps`.`periods`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boxsteps`.`periods` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `period` VARCHAR(50) NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `boxsteps`.`students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boxsteps`.`students` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `second_name` VARCHAR(100) NOT NULL,
  `DNI` VARCHAR(50) NULL,
  `email` VARCHAR(100) NULL,
  `address` TEXT NOT NULL,
  `mobile` VARCHAR(50) NULL,
  `phone` VARCHAR(50) NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `boxsteps`.`courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boxsteps`.`courses` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `grade` VARCHAR(50) NOT NULL,
  `section` VARCHAR(50) NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `periods_id` INT UNSIGNED NOT NULL,
  `students_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_courses_periods`
    FOREIGN KEY (`periods_id`)
    REFERENCES `boxsteps`.`periods` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_courses_students`
    FOREIGN KEY (`students_id`)
    REFERENCES `boxsteps`.`students` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE INDEX `fk_courses_periods_idx` ON `boxsteps`.`courses` (`periods_id` ASC);

CREATE INDEX `fk_courses_students_idx` ON `boxsteps`.`courses` (`students_id` ASC);


-- -----------------------------------------------------
-- Table `boxsteps`.`knowledge_areas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boxsteps`.`knowledge_areas` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `knowledge_area` VARCHAR(100) NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `boxsteps`.`conceptual_sections`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boxsteps`.`conceptual_sections` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `conceptual_section` VARCHAR(100) NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `knowledge_areas_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_conc_sect_know_area`
    FOREIGN KEY (`knowledge_areas_id`)
    REFERENCES `boxsteps`.`knowledge_areas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE INDEX `fk_conc_sect_know_area_idx` ON `boxsteps`.`conceptual_sections` (`knowledge_areas_id` ASC);


-- -----------------------------------------------------
-- Table `boxsteps`.`plans`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boxsteps`.`plans` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `procedimental_section` TEXT NOT NULL,
  `actitudinal_section` TEXT NOT NULL,
  `competences` TEXT NOT NULL,
  `indicators` TEXT NOT NULL,
  `teaching_strategy` TEXT NOT NULL,
  `teaching sequence` TEXT NOT NULL,
  `start_date` DATETIME NOT NULL,
  `end_date` DATETIME NOT NULL,
  `score` INT NULL,
  `completion_time` VARCHAR(50) NULL,
  `observations` TEXT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `periods_id` INT UNSIGNED NOT NULL,
  `courses_id` INT UNSIGNED NOT NULL,
  `conceptual_sections_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_plans_periods`
    FOREIGN KEY (`periods_id`)
    REFERENCES `boxsteps`.`periods` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_plans_courses`
    FOREIGN KEY (`courses_id`)
    REFERENCES `boxsteps`.`courses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_plans_conc_sect`
    FOREIGN KEY (`conceptual_sections_id`)
    REFERENCES `boxsteps`.`conceptual_sections` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE INDEX `fk_plans_periods_idx` ON `boxsteps`.`plans` (`periods_id` ASC);

CREATE INDEX `fk_plans_courses_idx` ON `boxsteps`.`plans` (`courses_id` ASC);

CREATE INDEX `fk_plans_conc_sect_idx` ON `boxsteps`.`plans` (`conceptual_sections_id` ASC);


-- -----------------------------------------------------
-- Table `boxsteps`.`resources`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boxsteps`.`resources` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `resource` VARCHAR(100) NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `plans_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_resources_plans`
    FOREIGN KEY (`plans_id`)
    REFERENCES `boxsteps`.`plans` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE INDEX `fk_resources_plans_idx` ON `boxsteps`.`resources` (`plans_id` ASC);


-- -----------------------------------------------------
-- Table `boxsteps`.`states`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boxsteps`.`states` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `state` VARCHAR(50) NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`));

CREATE UNIQUE INDEX `uq_state` ON `boxsteps`.`states` (`state` ASC);


-- -----------------------------------------------------
-- Table `boxsteps`.`notifications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boxsteps`.`notifications` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `notification` TEXT NOT NULL,
  `url` TEXT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `boxsteps`.`conditions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boxsteps`.`conditions` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `states_id` INT UNSIGNED NOT NULL,
  `plans_id` INT UNSIGNED NULL,
  `users_id` INT UNSIGNED NULL,
  `messages_id` INT UNSIGNED NULL,
  `notifications_id` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_conditions_messages`
    FOREIGN KEY (`messages_id`)
    REFERENCES `boxsteps`.`messages` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_conditions_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `boxsteps`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_conditions_states`
    FOREIGN KEY (`states_id`)
    REFERENCES `boxsteps`.`states` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_conditions_plans`
    FOREIGN KEY (`plans_id`)
    REFERENCES `boxsteps`.`plans` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cond_noti`
    FOREIGN KEY (`notifications_id`)
    REFERENCES `boxsteps`.`notifications` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE INDEX `fk_conditions_messages_idx` ON `boxsteps`.`conditions` (`messages_id` ASC);

CREATE INDEX `fk_conditions_users_idx` ON `boxsteps`.`conditions` (`users_id` ASC);

CREATE INDEX `fk_conditions_states_idx` ON `boxsteps`.`conditions` (`states_id` ASC);

CREATE INDEX `fk_conditions_plans_idx` ON `boxsteps`.`conditions` (`plans_id` ASC);

CREATE INDEX `fk_cond_noti_idx` ON `boxsteps`.`conditions` (`notifications_id` ASC);


-- -----------------------------------------------------
-- Table `boxsteps`.`evaluation_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boxsteps`.`evaluation_types` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `evaluation_type` VARCHAR(5) NOT NULL,
  `maximum_qualification` VARCHAR(50) NOT NULL,
  `minimum_qualification` VARCHAR(50) NOT NULL,
  `approved_qualification` VARCHAR(50) NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `boxsteps`.`evaluations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boxsteps`.`evaluations` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `representative_percentage` VARCHAR(5) NOT NULL,
  `start_date` DATETIME NOT NULL,
  `end_date` DATETIME NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `courses_id` INT UNSIGNED NOT NULL,
  `evaluation_types_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_evaluations_courses`
    FOREIGN KEY (`courses_id`)
    REFERENCES `boxsteps`.`courses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_evaluations_eval_type`
    FOREIGN KEY (`evaluation_types_id`)
    REFERENCES `boxsteps`.`evaluation_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE INDEX `fk_evaluations_courses_idx` ON `boxsteps`.`evaluations` (`courses_id` ASC);

CREATE INDEX `fk_evaluations_eval_type_idx` ON `boxsteps`.`evaluations` (`evaluation_types_id` ASC);


-- -----------------------------------------------------
-- Table `boxsteps`.`evaluation_contents`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boxsteps`.`evaluation_contents` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `evaluations_id` INT UNSIGNED NOT NULL,
  `conceptual_sections_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_eval_cont_conc_sect`
    FOREIGN KEY (`conceptual_sections_id`)
    REFERENCES `boxsteps`.`conceptual_sections` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_eval_cont_evaluations`
    FOREIGN KEY (`evaluations_id`)
    REFERENCES `boxsteps`.`evaluations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE INDEX `fk_eval_cont_conc_sect_idx` ON `boxsteps`.`evaluation_contents` (`conceptual_sections_id` ASC);

CREATE INDEX `fk_eval_cont_evaluations_idx` ON `boxsteps`.`evaluation_contents` (`evaluations_id` ASC);


-- -----------------------------------------------------
-- Table `boxsteps`.`evaluation_scales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boxsteps`.`evaluation_scales` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `notation` VARCHAR(50) NOT NULL,
  `maximum_equivalent` VARCHAR(50) NULL,
  `minimum_equivalent` VARCHAR(50) NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `evaluation_types_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_eval_scal_eval_type`
    FOREIGN KEY (`evaluation_types_id`)
    REFERENCES `boxsteps`.`evaluation_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE INDEX `fk_eval_scal_eval_type_idx` ON `boxsteps`.`evaluation_scales` (`evaluation_types_id` ASC);


-- -----------------------------------------------------
-- Table `boxsteps`.`qualifications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boxsteps`.`qualifications` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `qualification` VARCHAR(50) NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `evaluations_id` INT UNSIGNED NOT NULL,
  `students_id` INT UNSIGNED NOT NULL,
  `evaluation_scales_id` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_qual_eval`
    FOREIGN KEY (`evaluations_id`)
    REFERENCES `boxsteps`.`evaluations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_qual_stud`
    FOREIGN KEY (`students_id`)
    REFERENCES `boxsteps`.`students` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_qual_eval_scal`
    FOREIGN KEY (`evaluation_scales_id`)
    REFERENCES `boxsteps`.`evaluation_scales` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE INDEX `fk_qual_eval_idx` ON `boxsteps`.`qualifications` (`evaluations_id` ASC);

CREATE INDEX `fk_qual_stud_idx` ON `boxsteps`.`qualifications` (`students_id` ASC);

CREATE INDEX `fk_qual_eval_scal_idx` ON `boxsteps`.`qualifications` (`evaluation_scales_id` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
